CREATE TABLE items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(100) UNIQUE,
    hsn_code VARCHAR(50),
    item_type VARCHAR(20) NOT NULL,
    unit VARCHAR(50),
    category VARCHAR(100),
    sale_price DECIMAL(10,2),
    sale_price_type VARCHAR(20),
    sale_discount DECIMAL(10,2),
    sale_discount_type VARCHAR(20),
    purchase_price DECIMAL(10,2),
    purchase_price_type VARCHAR(20),
    tax_rate VARCHAR(20),
    opening_quantity DECIMAL(10,2),
    opening_price DECIMAL(10,2),
    opening_date TIMESTAMP,
    min_stock DECIMAL(10,2),
    location VARCHAR(255),
    image_url VARCHAR(500),
    merchant_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (merchant_id) REFERENCES users(id)
);
